CREATE TABLE comics (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cover VARCHAR(255) NOT NULL,
    title VARCHAR(100) NOT NULL,
    synopsis TEXT NOT NULL,
    author VARCHAR(50) NOT NULL,
    artist VARCHAR(50) NOT NULL,
    type VARCHAR(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);