DROP TABLE chapters;
CREATE TABLE chapters(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    comic_id INT NOT NULL,
    number BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chapters_comics FOREIGN KEY(comic_id) REFERENCES comics(id) ON DELETE CASCADE ON UPDATE CASCADE
)